dotfiles:
  - { source: "gitconfig", dest: ".gitconfig" }
  - { source: "gitignore_global", dest: ".gitignore_global" }
  - { source: ".zshrc", dest: ".zshrc" }
  - { source: ".tmux.conf", dest: ".tmux.conf" }
  - { source: ".vimrc", dest: ".vimrc" }
  - { source: "nvim", dest: ".config/nvim" }
  - { source: "ghostty/config", dest: ".config/ghostty/config" }
  - { source: "gemini-settings.json", dest: ".gemini/settings.json" }
  - { source: "claude-settings.json", dest: ".claude/settings.json" }
  - { source: "AGENT.md", dest: ".gemini/GEMINI.md" }
  - { source: "AGENT.md", dest: ".claude/CLAUDE.md" }

optional_dotfiles:
  - { source: ".editorconfig", dest: ".editorconfig", description: "global editorconfig file" }

macos_services_to_restart:
  - Dock
  - Finder
  - WindowManager
  - SystemUIServer
  - Spotlight

homebrew_formulae:
  - cmake
  - container
  - fd
  - fzf
  - jdtls
  - neovim
  - ripgrep
  - tmux
  - wget

homebrew_casks:
  - anki
  - ghostty

optional_homebrew_formulae:
  - gh

optional_homebrew_casks:
  - blackhole-2ch
  - crossover
  - dolphin
  - iina
  - ilok-license-manager
  - retroarch-metal
  - steam
  - stremio
  - valhalla-supermassive
  - vlc

terminal_profiles: ["Basic", "Pro", "Clear Dark"]
terminal_settings:
  - { key: "shellExitAction", type: "integer", value: "1" }
  - { key: "BackgroundAlphaInactive", type: "real", value: "0.5" }
  - { key: "BackgroundSettingsForInactiveWindows", type: "bool", value: "true" }

managed_login_items:
  - { type: "TeamIdentifier", value: "MXGJJ98X76", comment: "Steam", disposition: "Disallowed" }

manage_login_items: false
install_packages: true
configure_system_audio: true
configure_night_shift: true
