- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  register: brew_update
  failed_when: brew_update is failed and 'Could not update' not in brew_update.msg

- name: Install Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    upgrade: true
  loop: "{{ homebrew_formulae }}"

- name: Install Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    upgrade: true
  loop: "{{ homebrew_casks }}"

- name: Install optional Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: present
    upgrade: true
  loop: "{{ optional_homebrew_formulae }}"
  when: install_optional | default(false) | bool

- name: Install optional Homebrew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    upgrade: true
  loop: "{{ optional_homebrew_casks }}"
  when: install_optional | default(false) | bool

- name: Remove unused Homebrew dependencies (autoremove)
  ansible.builtin.command: brew autoremove
  register: brew_autoremove
  changed_when: brew_autoremove.stdout != ""
