#!/usr/bin/env python3
import sys
import os

# Add the repository root to sys.path
current_dir = os.path.dirname(os.path.abspath(__file__))
repo_root = os.path.dirname(current_dir)
sys.path.insert(0, repo_root)

from install import install_dotfiles

if __name__ == "__main__":
    install_dotfiles()
