#!/usr/bin/env python3
import sys
import os

# Add repo root to sys.path to allow importing lib
repo_root = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, repo_root)

from lib.notifications import main

if __name__ == "__main__":
    main()
